name: Check

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum

permissions: read-all

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build

      - name: Test
        run: go test ./...
