# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release

on:
  release:
    types: [published]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows, darwin, linux]
        arch: [amd64, 386]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -o release/${{ matrix.platform }}-${{ matrix.arch }}
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch }}
          path: release/${{ matrix.platform }}-${{ matrix.arch }}
