name: Checks

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - .github/workflows/stable-check.yml

permissions: read-all

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up repo
        uses: actions/checkout@v6.0.3

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Build
        run: go build

      - name: Test
        run: go test ./...
